project:
  directory: ace

gromacs:
  command: gmx

defaults:
  nsteps:
    npt: 0
    prod: 100000

reference:
  n_single_point_snapshots: 1000

systems:
  - topology: ../common/topol.top
    templates:
      ACE: ../common/ace.gro
    mdp:
      em: ../common/mdp/em.mdp
      npt: ../common/mdp/npt.mdp
      prod: ../common/mdp/nvt.mdp
    charge: -1
    multiplicity: 1
    box: [15.7107, 15.7107, 15.7107, 90, 90, 90]

  - topology: ../common/topol-ions.top
    templates:
      ACE: ../common/ace.gro
    mdp:
      em: ../common/mdp/em.mdp
      npt: ../common/mdp/npt.mdp
      prod: ../common/mdp/nvt.mdp
    charge: 1
    multiplicity: 1
    box: [15.7480, 15.7480, 15.7480, 90, 90, 90]
    bias:
      plumed_file: ./plumed-001.dat

  - topology: ../common/topol-ions.top
    templates:
      ACE: ../common/ace.gro
    mdp:
      em: ../common/mdp/em.mdp
      npt: ../common/mdp/npt.mdp
      prod: ../common/mdp/nvt.mdp
    charge: 1
    multiplicity: 1
    box: [15.7480, 15.7480, 15.7480, 90, 90, 90]
    bias:
      plumed_file: ./plumed-002.dat
