project:
  directory: ace

gromacs:
  command: gmx

defaults:
  nsteps:
    npt: 0
    nvt: 100000

reference:
  n_single_point_snapshots: 1000

systems:
  - topology: ./topol.top
    coordinates: ./ace.gro
    charge: -1
    multiplicity: 1
    box: [15.7107, 15.7107, 15.7107, 90, 90, 90]

  - topology: ./topol-ions.top
    coordinates: ./ace.gro
    charge: 1
    multiplicity: 1
    box: [15.7480, 15.7480, 15.7480, 90, 90, 90]
    bias:
      plumed_file: ./plumed-001.dat

  - topology: ./topol-ions.top
    coordinates: ./ace.gro
    charge: 1
    multiplicity: 1
    box: [15.7480, 15.7480, 15.7480, 90, 90, 90]
    bias:
      plumed_file: ./plumed-002.dat
