name: bff
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - pip
  - ipython
  - ipykernel
  - ipywidgets
  - jupyterlab
  - notebook
  - numpy
  - scipy
  - matplotlib
  - pyyaml
  - mdanalysis
  - typer
  - gmxtop
  - pytest
  - ruff
  - mkdocs
  - mkdocs-material
  - pymdown-extensions
  - build
  - twine
