trainset_dir: ./validation-trainset
parameters: ../05-learning/posterior-samples.yaml
specs: ../02-training-data/trainset/specs.yaml
systems:
  - assets: ../01-prepare/colvars/ace-colvars/training/system-000
    n_steps: 1000
  - assets: ../01-prepare/colvars/ace-colvars/training/system-001
    n_steps: 1000
  - assets: ../01-prepare/colvars/ace-colvars/training/system-002
    n_steps: 1000
compress: false
cleanup: true
store: ["xtc"]
gmx_cmd: gmx
job_scheduler: local
