sample:
  dir: ../03-sample-local
  start: 1
  stop: -1
  step: 1
  progress_stride: 10

reference:
  start: 1
  stop: -1
  step: 1
  systems:
    - coordinates: ../02-evaluate-import/system-000/system.gro
      topology: ../02-evaluate-import/system-000/system.top
      trajectory: ../02-evaluate-import/system-000/trajectory.xtc
      routines:
        - routine: rdf
          mol_resname: ACE
          r_range: [1, 7]
          smooth: false
        - routine: hb
          mol_resname: ACE
    - coordinates: ../02-evaluate-import/system-001/system.gro
      topology: ../02-evaluate-import/system-001/system.top
      trajectory: ../02-evaluate-import/system-001/trajectory.xtc
      routines:
        - routine: rdf
          mol_resname: ACE
          r_range: [1, 7]
          smooth: false
        - routine: hb
          mol_resname: ACE
        - routine: ../inputs/restraint.py:distance_distribution
          atom_pair: [C2, CAL]
          r_range: [2.0, 5.0]
    - coordinates: ../02-evaluate-import/system-002/system.gro
      topology: ../02-evaluate-import/system-002/system.top
      trajectory: ../02-evaluate-import/system-002/trajectory.xtc
      routines:
        - routine: rdf
          mol_resname: ACE
          r_range: [1, 7]
          smooth: false
        - routine: hb
          mol_resname: ACE
        - routine: ../inputs/restraint.py:distance_distribution
          atom_pair: [C2, CAL]
          r_range: [4.0, 6.0]

run:
  in_memory: true
  gc_collect: false
  maxtasksperchild: 100

output:
  path: ./qoi
  log: ./out.log
  write_raw: true
