output_dir: ./snapshots
job_scheduler: local
cp2k_cmd: cp2k.psmp
single_atoms: true
snapshot_md_steps: 1
train_fraction: 0.8
seed: 2026

systems:
  - assets: ../02-assets/reference/system-000
  - assets: ../02-assets/reference/system-001
  - assets: ../02-assets/reference/system-002
