mode: run
output_dir: ./
job_scheduler: local
cp2k_cmd: cp2k.psmp
single_atoms: true
snapshot_md_steps: 1
train_fraction: 0.8
seed: 2026

systems:
  - assets: ../01-build-colvars/reference/system-000
  - assets: ../01-build-colvars/reference/system-001
  - assets: ../01-build-colvars/reference/system-002
