output_dir: ./snapshots
job_scheduler: slurm
cp2k_cmd: cp2k.psmp
single_atoms: true
snapshot_md_steps: 10
train_fraction: 0.8
seed: 2026
cleanup_snapshots: true
collection_wait_seconds: 60

systems:
  - assets: ../02-assets/reference/system-000
  - assets: ../02-assets/reference/system-001
  - assets: ../02-assets/reference/system-002

slurm:
  max_parallel_jobs: 100
  sbatch:
    constraint: gen-a
    time: "04:00:00"
    mem: 20G
    nodes: 1
    ntasks-per-node: 8
  setup:
    - source /uochb/soft/a/spack/20221129-git/share/spack/setup-env.sh
    - spack load cp2k+elpa+libint
    - export OMP_NUM_THREADS=1
    - export SLURM_MPI_TYPE=pmix_v3
    - export LD_LIBRARY_PATH=/uochb/soft/core/pmix/pmix-3.2.3/lib:$LD_LIBRARY_PATH
