log: ./out.log
datasets:
  rdf:
    data: ../04-analyze/qoi-rdf.pt
    mean: sigmoid
  hb:
    data: ../04-analyze/qoi-hb.pt
    mean: 0
  dist:
    data: ../04-analyze/qoi-dist.pt
    mean: 0
fit:
  model_dir: ./models
  reuse_models: true
  n_hyper_max: 200
  committee_size: 1
  test_fraction: 0.2
  device: cuda
