log: ../06-learn/out.log
specs: ../03-sample-local/specs.yaml
models:
  rdf: ../05-fit/models/rdf.lgp
  hb: ../05-fit/models/hb.lgp
  dist: ../05-fit/models/dist.lgp
mcmc:
  priors_disttype: normal
  total_steps: 10000
  warmup: 2000
  progress_stride: 1000
  checkpoint: ../06-learn/mcmc-checkpoint.pt
  posterior: ../06-learn/posterior.pt
  priors: ../06-learn/priors.pt
  restart: false
  device: cuda
  rhat_tol: 1.05
