mode: import
reference_dir: ./

systems:
  - topology: ../01-build-colvars/reference/system-000/system.top
    coordinates: ../01-build-colvars/reference/system-000/system.gro
    trajectory: ../inputs/reference-trajectories/pos-000.xtc
  - topology: ../01-build-colvars/reference/system-001/system.top
    coordinates: ../01-build-colvars/reference/system-001/system.gro
    trajectory: ../inputs/reference-trajectories/pos-001.xtc
  - topology: ../01-build-colvars/reference/system-002/system.top
    coordinates: ../01-build-colvars/reference/system-002/system.gro
    trajectory: ../inputs/reference-trajectories/pos-002.xtc
