campaign_dir: ./
parameters: ../06-learn/posterior-samples.yaml
specs: ../03-sample/specs.yaml
source: ../01-build
systems:
  - system_id: acetate
    n_steps: 1000
  - system_id: acetate-contact
    n_steps: 1000
  - system_id: acetate-separated
    n_steps: 1000
compress: false
cleanup: true
store: ["xtc"]
gmx_cmd: gmx
job_scheduler: local
