trainset:
  dir: ../03-training-trjs/trainset
  start: 1
  stop: -1
  step: 1
  progress_stride: 10

refset:
  start: 1
  stop: -1
  step: 1
  systems:
    - coordinates: ../01-prepare/colvars/ace-colvars/reference/window-000/system.gro
      topology: ../01-prepare/colvars/ace-colvars/reference/window-000/system.top
      trajectory: ../02-reference-trjs/pos-000.xtc
      routines:
        - routine: rdf
          mol_resname: ACE
          r_range: [1, 7]
          smooth: false
        - routine: hb
          mol_resname: ACE
    - coordinates: ../01-prepare/colvars/ace-colvars/reference/window-001/system.gro
      topology: ../01-prepare/colvars/ace-colvars/reference/window-001/system.top
      trajectory: ../02-reference-trjs/pos-001.xtc
      routines:
        - routine: rdf
          mol_resname: ACE
          r_range: [1, 7]
          smooth: false
        - routine: hb
          mol_resname: ACE
        - routine: ./restraint.py:distance_distribution
          atom_pair: [C2, CAL]
          r_range: [2.0, 5.0]
    - coordinates: ../01-prepare/colvars/ace-colvars/reference/window-002/system.gro
      topology: ../01-prepare/colvars/ace-colvars/reference/window-002/system.top
      trajectory: ../02-reference-trjs/pos-002.xtc
      routines:
        - routine: rdf
          mol_resname: ACE
          r_range: [1, 7]
          smooth: false
        - routine: hb
          mol_resname: ACE
        - routine: ./restraint.py:distance_distribution
          atom_pair: [C2, CAL]
          r_range: [4.0, 6.0]

run:
  in_memory: true
  gc_collect: false
  maxtasksperchild: 100

output:
  path: ./qoi
  log: ./out.log
  write_raw: true
