mol_resname: ACE
trainset_dir: ./trainset
systems:
  - topology: ../01-prepare/ace/training/window-000.top
    coordinates: ../01-prepare/ace/training/window-000.gro
    mdp:
      em: ../01-prepare/ace/training/em.mdp
      prod: ../01-prepare/ace/training/window-000.mdp
    index: ../01-prepare/ace/training/window-000.ndx
    bias: null
    n_steps: 550000
  - topology: ../01-prepare/ace/training/window-001.top
    coordinates: ../01-prepare/ace/training/window-001.gro
    mdp:
      em: ../01-prepare/ace/training/em.mdp
      prod: ../01-prepare/ace/training/window-001.mdp
    index: ../01-prepare/ace/training/window-001.ndx
    bias: ../01-prepare/ace/training/window-001.bias.plumed.dat
    n_steps: 550000
  - topology: ../01-prepare/ace/training/window-002.top
    coordinates: ../01-prepare/ace/training/window-002.gro
    mdp:
      em: ../01-prepare/ace/training/em.mdp
      prod: ../01-prepare/ace/training/window-002.mdp
    index: ../01-prepare/ace/training/window-002.ndx
    bias: ../01-prepare/ace/training/window-002.bias.plumed.dat
    n_steps: 550000
bounds:
  charge C2: [0.0, 1.0]
  charge O1 O2: [-0.8, -0.3]
  charge C1: [-1.0, 0.3]
  charge H1 H2 H3: [-0.3, 0.3]
implicit_atoms: [C2]
total_charge: -0.80
n_samples: 10
compress: false
cleanup: true
store: ['xtc']
gmx_cmd: gmx
job_scheduler: slurm
slurm:
  max_parallel_jobs: 1500
  sbatch:
    job_name: ace-train
    nodes: 1
    ntasks_per_node: 1
    cpus_per_task: 1
    mem: 1G
    time: 00:40:00
    partition: a36_any
  setup:
    - source /uochb/soft/a/spack/20221129-git/share/spack/setup-env.sh
    - spack load gromacs@2022.4 ~mpi
    - export WORKDIR=/dev/shm/$USER/$SLURM_JOB_ID
    - mkdir -p $WORKDIR
    - cd $WORKDIR
  teardown:
    - rm -rf $WORKDIR
