reference_dir: ./assets
job_scheduler: slurm
cp2k_cmd: cp2k.psmp
single_atoms: true
snapshot_md_steps: 100
train_fraction: 0.8
seed: 2026

systems:
  - assets: ../01-prepare/colvars/reference/system-000
    # Optional per-system overrides:
    md: ./inputs/md-0.inp
    # sp: ./inputs/revpbe0-sp.inp
  - assets: ../01-prepare/colvars/reference/system-001
    md: ./inputs/md-1.inp
  - assets: ../01-prepare/colvars/reference/system-002
    md: ./inputs/md-2.inp

slurm:
  max_parallel_jobs: 100
  sbatch:
    constraint: gen-a
    time: "04:00:00"
    mem: 20G
    nodes: 1
    ntasks-per-node: 8
  setup:
    - source /uochb/soft/a/spack/20221129-git/share/spack/setup-env.sh
    # - source /uochb/soft/b/spack/20221211-git/share/spack/setup-env.sh
    - spack load cp2k+elpa+libint
    - export OMP_NUM_THREADS=1
    - export SLURM_MPI_TYPE=pmix_v3
    - export LD_LIBRARY_PATH=/uochb/soft/core/pmix/pmix-3.2.3/lib:$LD_LIBRARY_PATH

