fn_log: out.log
fn_specs: ../04-qoi/qoi-specs.yaml
qoi:
  - rdf
  - hb
  - restr
datasets:
  rdf:
    data: ../04-qoi/qoi-rdf.pt
    mean: sigmoid
  hb:
    data: ../04-qoi/qoi-hb.pt
    mean: 0
  restr:
    data: ../04-qoi/qoi-restr.pt
    mean: 0
lgp_train:
  n_hyper_max: 200
  committee_size: 1
  test_fraction: 0.2
  device: cuda:0
mcmc:
  priors_disttype: normal
  max_iter: 1000
  fn_checkpoint: mcmc-checkpoint.pt
  fn_posterior: posterior.pt
  fn_priors: priors.pt
  restart: True
  device: cuda:0
