trainset_dir: ./validation-trainset
parameters: ../06-learn/posterior-samples.yaml
specs: ../03-training-trjs/trainset/specs.yaml
systems:
  - assets: ../01-prepare/colvars/ace-colvars/training/system-000
    n_steps: 1000
  - assets: ../01-prepare/colvars/ace-colvars/training/system-001
    n_steps: 1000
  - assets: ../01-prepare/colvars/ace-colvars/training/system-002
    n_steps: 1000
compress: false
cleanup: true
store: ["xtc"]
gmx_cmd: gmx
job_scheduler: local
