reference_dir: ./reference
job_scheduler: local
cp2k_cmd: ~/miniforge3/envs/cp2k/bin/cp2k.psmp
single_atoms: true
snapshot_md_steps: 1
train_fraction: 0.8
seed: 2026

systems:
  - assets: ../01-prepare/colvars/reference/system-000
    # Optional per-system overrides:
    # md: ./inputs/system-000-md.inp
    # sp: ./inputs/revpbe0-sp.inp
  - assets: ../01-prepare/colvars/reference/system-001
  - assets: ../01-prepare/colvars/reference/system-002
